version: '3.1'

services:
  springapp:
    image: 35.154.42.145:8081/spring-boot-mongo:${buildNo}
    ports:
    - 8082:8080
    - 50000:50000
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb@123
    networks:
    - springappbridge
    depends_on:
    - mongo

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    volumes:
    - mongodb:/data/db
    networks:
    - springappbridge

volumes:
  mongodb:
    driver: local

networks:
  springappbridge:
    driver: overlay
